### ISSUE TITLE
Mention go vet possible addition

### ISSUE THREAD

**Issue by ccoVeille** [ccoVeille/golangci-lint-config-examples#25]
Such as

```yaml
linters-settings:
  govet:
    enable:
      - unusedwrite
```
